### ISSUE TITLE
Инициализация базы данных

### ISSUE THREAD

**Issue by elakovnick24** [elakovnick24/SQL_Homework#1]
# Не могу проинициализировать базу данных

### Шаг 1 
- Запускаю контейнер 
`sudo docker-compose up -d`
- Смотрю лог 
`sudo docker-compose logs -f  `
Вижу, что есть коннект 
![image](https://user-images.githubusercontent.com/57618846/92811682-59de3e00-f3c7-11ea-9fc2-ed0f9372b337.png)

### Шаг 2 
Делаю третий пункт из условия задачи

> Запустить SUT (app-deadline.jar): для указания параметров подключения к БД можно использовать:

- Запускаю SUT 

`java -jar app-deadline.jar -P:jdbc.url=http://localhost:9999 -P:jdbc.user=app -P:jdbc.password=pass`

![image](https://user-images.githubusercontent.com/57618846/92812005-a45fba80-f3c7-11ea-93bf-7a36b8a93e78.png)

```
2020-09-11 00:36:39.870 [main] TRACE Application - {
    # application.conf @ jar:file:/Users/nikitaelakov/Downloads/SQL_Homework/app-deadline.jar!/application.conf: 6
    "application" : {
        # application.conf @ jar:file:/Users/nikitaelakov/Downloads/SQL_Homework/app-deadline.jar!/application.conf: 7
        "modules" : [
            # application.conf @ jar:file:/Users/nikitaelakov/Downloads/SQL_Homework/app-deadline.jar!/application.conf: 7
            "ru.netology.aqa.ApplicationKt.module"
        ]
    },
    # application.conf @ jar:file:/Users/nikitaelakov/Downloads/SQL_Homework/app-deadline.jar!/application.conf: 2
    "deployment" : {
        # application.conf @ jar:file:/Users/nikitaelakov/Downloads/SQL_Homework/app-deadline.jar!/application.conf: 3
        "port" : 9999
    },
    # Content hidden
    "security" : "***"
}

2020-09-11 00:36:39.985 [DefaultDispatcher-worker-1] INFO  Application - No ktor.deployment.watch patterns specified, automatic reload is not active
Exception in thread "DefaultDispatcher-worker-1" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:152)
        at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.callFunctionWithInjection(ApplicationEngineEnvironmentReloading.kt:392)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:340)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:33)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1$$special$$inlined$forEach$lambda$1.invoke(ApplicationEngineEnvironmentReloading.kt:287)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1$$special$$inlined$forEach$lambda$1.invoke(ApplicationEngineEnvironmentReloading.kt:33)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:320)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:33)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:286)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:33)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:302)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:284)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:137)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:257)
        at io.ktor.server.cio.CIOApplicationEngine$serverJob$1$1.invokeSuspend(CIOApplicationEngine.kt:52)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
Caused by: java.sql.SQLException: Cannot create JDBC driver of class 'com.mysql.cj.jdbc.Driver' for connect URL 'http://localhost:9999'
        at org.apache.commons.dbcp2.DriverFactory.createDriver(DriverFactory.java:75)
        at org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:472)
        at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:538)
        at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753)
        at org.apache.commons.dbutils.AbstractQueryRunner.prepareConnection(AbstractQueryRunner.java:319)
        at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:495)
        at ru.netology.aqa.service.UserService$register$2.invokeSuspend(UserService.kt:31)
        ... 5 more
Caused by: java.sql.SQLException: No suitable driver
        at org.apache.commons.dbcp2.DriverFactory.createDriver(DriverFactory.java:68)
        ... 11 more

```

Скорее всего прописал не правильный флаги параметров запуска сервиса

###  Инициализация 

Читаю подсказку 
> Поэтому вам нужно сходить на сайт-описание Docker Image MySQL и посмотреть, как при инициализации скармливать схему.

- На сайте был Docker был 
- и был еще вот здесь https://qastack.ru/programming/29145370/how-can-i-initialize-a-mysql-database-with-schema-in-a-docker-container 

Из того, что я понял (по-моему пока ,что ничего =) ) 

Нужно добавить в volumes что-то типа вот такого пути 

`- ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro`

**Верно или нет?** Я не пробовал так как ничего не понял 

Про вычистку данных наверное позже спрошу, как доберусь до этого шага) 

@ArRomanov

**Comment by ArRomanov** [comment]
1. Про volume верно, но написали некорректно. Через volume у нас объединяются директории, а не отдельные файлы. Правильнее будет так `- ./database:/docker-entrypoint-initdb.d:ro`
2. По команде запуска приложения тоже ошибка. В параметре **-P:jdbc.url** должен быть адрес к БД, как у вас было прописано в прошлом задании в **application.properties**
